"""
Pydantic models for request/response validation and structured outputs.
Ensures type safety and provides clear API contracts.
"""
from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field, HttpUrl
from datetime import datetime


class ForecastRequest(BaseModel):
    """Request model for forecast generation."""
    company_url: str = Field(
        ...,
        description="URL to the company's Screener.in page",
        example="https://www.screener.in/company/TCS/consolidated/"
    )
    quarters: int = Field(
        default=2,
        ge=1,
        le=4,
        description="Number of past quarters to analyze (1-4)"
    )
    include_market_data: bool = Field(
        default=True,
        description="Whether to include live market data in the analysis"
    )


class FinancialMetrics(BaseModel):
    """Structured financial metrics extracted from quarterly reports."""
    quarter: str = Field(..., description="Quarter identifier (e.g., 'Q3 FY24')")
    total_revenue: Optional[float] = Field(None, description="Total revenue in crores")
    net_profit: Optional[float] = Field(None, description="Net profit in crores")
    operating_margin: Optional[float] = Field(None, description="Operating margin percentage")
    revenue_growth_yoy: Optional[float] = Field(None, description="Year-over-year revenue growth %")
    profit_growth_yoy: Optional[float] = Field(None, description="Year-over-year profit growth %")
    eps: Optional[float] = Field(None, description="Earnings per share")
    additional_metrics: Dict[str, Any] = Field(
        default_factory=dict,
        description="Additional financial metrics"
    )


class QualitativeInsights(BaseModel):
    """Insights from qualitative analysis of earnings calls and transcripts."""
    key_themes: List[str] = Field(
        default_factory=list,
        description="Recurring themes identified across transcripts"
    )
    management_sentiment: str = Field(
        ...,
        description="Overall management sentiment (positive/neutral/negative)"
    )
    forward_looking_statements: List[str] = Field(
        default_factory=list,
        description="Key forward-looking statements from management"
    )
    risks_identified: List[str] = Field(
        default_factory=list,
        description="Risks and concerns mentioned"
    )
    opportunities_identified: List[str] = Field(
        default_factory=list,
        description="Growth opportunities and positive indicators"
    )
    strategic_initiatives: List[str] = Field(
        default_factory=list,
        description="Strategic initiatives and focus areas"
    )


class MarketData(BaseModel):
    """Live market data for the company."""
    symbol: str = Field(..., description="Stock symbol")
    current_price: Optional[float] = Field(None, description="Current stock price")
    timestamp: datetime = Field(default_factory=datetime.utcnow, description="Data timestamp")
    additional_data: Dict[str, Any] = Field(
        default_factory=dict,
        description="Additional market metrics"
    )


class ForecastOutput(BaseModel):
    """
    Structured forecast output - the main result of agent analysis.
    This is the core deliverable that synthesizes all tool outputs.
    """
    summary: str = Field(
        ...,
        description="Executive summary of the forecast"
    )

    financial_trends: List[str] = Field(
        default_factory=list,
        description="Key financial trends identified (revenue, margins, profitability)"
    )

    qualitative_assessment: str = Field(
        ...,
        description="Synthesis of management outlook and sentiment"
    )

    outlook_next_quarter: str = Field(
        ...,
        description="Forecast and expectations for the upcoming quarter"
    )

    key_risks: List[str] = Field(
        default_factory=list,
        description="Significant risks that may impact future performance"
    )

    key_opportunities: List[str] = Field(
        default_factory=list,
        description="Growth opportunities and positive catalysts"
    )

    confidence_level: str = Field(
        default="medium",
        description="Confidence level of the forecast (high/medium/low)"
    )

    disclaimer: str = Field(
        default="This forecast is generated by an AI agent based on historical data and does not constitute investment advice.",
        description="Legal disclaimer"
    )


class ForecastResponse(BaseModel):
    """Complete API response for forecast requests."""
    request_id: str = Field(..., description="Unique request identifier")
    company_symbol: str = Field(..., description="Company symbol")
    timestamp: datetime = Field(default_factory=datetime.utcnow)

    # Forecast output
    forecast: ForecastOutput = Field(..., description="The generated forecast")

    # Supporting data
    financial_metrics: List[FinancialMetrics] = Field(
        default_factory=list,
        description="Extracted financial metrics by quarter"
    )
    qualitative_insights: Optional[QualitativeInsights] = Field(
        None,
        description="Insights from qualitative analysis"
    )
    market_data: Optional[MarketData] = Field(
        None,
        description="Live market data"
    )

    # Metadata
    quarters_analyzed: int = Field(..., description="Number of quarters analyzed")
    tools_used: List[str] = Field(
        default_factory=list,
        description="List of tools invoked during analysis"
    )
    execution_time_seconds: Optional[float] = Field(
        None,
        description="Total execution time"
    )

    class Config:
        json_schema_extra = {
            "example": {
                "request_id": "req_123abc",
                "company_symbol": "TCS",
                "timestamp": "2025-01-15T10:30:00",
                "forecast": {
                    "summary": "TCS shows strong revenue growth with improving margins...",
                    "financial_trends": [
                        "Revenue growth of 5.2% YoY in Q3 FY24",
                        "Operating margins improved to 25.1%"
                    ],
                    "qualitative_assessment": "Management expressed confidence in deal pipeline...",
                    "outlook_next_quarter": "Expect continued growth driven by cloud and digital transformation...",
                    "key_risks": ["Macro headwinds", "Currency fluctuations"],
                    "key_opportunities": ["Growing deal pipeline", "Cloud adoption"],
                    "confidence_level": "high"
                },
                "quarters_analyzed": 2,
                "tools_used": ["FinancialDataExtractor", "QualitativeAnalysis", "MarketData"]
            }
        }
